//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageRederForRX {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlProperty {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlProperty() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PageRederForRX.SqlProperty", typeof(SqlProperty).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 select code,name from (
        ///select vtype code,vtype name from TBUDT_BasicAllCtr GROUP BY vtype 
        ///union all 
        ///select vtype code,vtype name from TBUDT_BasicCodeToN GROUP BY vtype 
        ///union all 
        ///select vtype code,vtype name from TBUDT_BasicListCap group by vtype) a where a.code!=&apos;&apos;  group by code,name 的本地化字符串。
        /// </summary>
        internal static string Basic_vtype_paramcode {
            get {
                return ResourceManager.GetString("Basic_vtype_paramcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bug&amp;建议:
        ///	实施一组: 盛发发|余治发
        ///已知问题：
        ///	1.暂时无法识别钉钉布局
        ///	2.从表布局无法绘制
        ///	3.从表部分数据无法更改 的本地化字符串。
        /// </summary>
        internal static string ErrorNote {
            get {
                return ResourceManager.GetString("ErrorNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///	ibillid,
        ///	vType,
        ///	vKeyid,
        ///	vKeyName,
        ///	tgp.name vName,
        ///	vkeyValue,
        ///	vHzrxField1,
        ///	vHzrxField2,
        ///	tba.IOrderId,
        ///	vRemarks,&apos;TBUDT_BasicAllCtr&apos; tableName
        ///	from TBUDT_BasicAllCtr tba
        ///	LEFT JOIN TPZJK_GetParamCode tgp ON tba.vkeyname = tgp.code 
        ///WHERE
        ///	tba.ibillid = &apos;{getIbilldId()}&apos;{whereIs}
        ///	union all 
        ///	SELECT
        ///	ibillid,
        ///	vType,
        ///	vKeyid,
        ///	vKeyName,
        ///	tgp.name vName,
        ///	vkeyValue,
        ///	vHzrxField1,
        ///	vHzrxField2,
        ///	tba.IOrderId,
        ///	vRemarks,&apos;TBUDT_BasicCodeToN&apos; tableName
        ///	from TBUDT_BasicCo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string getBasicSQL {
            get {
                return ResourceManager.GetString("getBasicSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select vwidth,vHeight from TBUDT_ModeLayout where vid = &apos;{ChartLayoutListBox.SelectedItem}&apos; 的本地化字符串。
        /// </summary>
        internal static string query_ChartLayout_For_TBUDT_ModeLayout {
            get {
                return ResourceManager.GetString("query_ChartLayout_For_TBUDT_ModeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select vID,vPID,vFieldCode,vFieldName,vWidth,vHeight,vIsShow,vAlign,IOrderID,vDraj,vGroundColor,vOrgID,vfrmtype,vChange,vtexttype,vtotalrow,vtotalrowtype,vgroup from TBUDT_ChartLayout where vpid = &apos;{ChartLayoutListBox.SelectedItem}&apos; order by IOrderID 的本地化字符串。
        /// </summary>
        internal static string query_TBUDT_ChartLayout {
            get {
                return ResourceManager.GetString("query_TBUDT_ChartLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select vID,vFieldCode,vMainLable,vLable,vTop,vLeft,vWidth,vHeight,vColor,vGroundColor,IOrderID,vfrmtype,ISNULL(vIsShow, &apos;1&apos;) vIsShow ,vgroup,vChange,vtexttype,vDefault  from TBUDT_EditLayout where vpid =&apos;{MainListBox.SelectedItem}&apos; 的本地化字符串。
        /// </summary>
        internal static string query_TBUDT_EditLayout {
            get {
                return ResourceManager.GetString("query_TBUDT_EditLayout", resourceCulture);
            }
        }
    }
}
